[project]
name = "example-lambda-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Masaki Kobayashi", email = "bayashi.cl@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.31",
    "example-common",
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "boto3-stubs[lambda]>=1.40.31",
    "mypy>=1.18.1",
]

[tool.uv.sources]
example-common = { workspace = true }
