[project]
name = "example-common"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Masaki Kobayashi", email = "bayashi.cl@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.9",
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.18.1",
]
