[project]
name = "example-lambda-b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Masaki Kobayashi", email = "bayashi.cl@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "example-common",
    "httpx>=0.28.1",
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.18.1",
]

[tool.uv.sources]
example-common = { workspace = true }
